"""What Autodesk's published 2027 reference changed here, pinned.

On 2026-09-08 a curated extraction of the Inventor 2027 API User's Manual and
Reference Manual was read against this repository. Most of it confirmed what
had been measured; a handful of things it settled changed code, and each of
those is held here so the change cannot quietly revert.

The rule the changes follow is in `docs/DECISIONS.md` under "A published
signature outranks a guess and not a measurement": a path that had never run
against an Inventor was moved to the documented call outright, and a path that
had been measured kept its measured route first, with the documented one behind
it. These tests are the countable half of that rule.
"""

from __future__ import annotations

import pytest

from inventor_mcp.backend.com import backend as com
from inventor_mcp.backend.com.constants import FALLBACK, HEALTH_STATUS_NAMES


class TestTheHealthStatusNames:
    """`HealthStatusEnum` is not in 2027.1's type library, so the published
    page is the only source there will be on that release. 11778 is the value
    seven just-built features reported, and the page calls it up to date."""

    def test_the_observed_healthy_value_is_the_published_up_to_date(self):
        assert FALLBACK["kUpToDateHealth"] == 11778
        assert 11778 in com._OBSERVED_HEALTHY
        assert HEALTH_STATUS_NAMES[11778] == "kUpToDateHealth"

    def test_every_published_member_is_present_and_contiguous(self):
        """Fourteen members, 11777 through 11790, as the page lists them."""
        health = {name: value for name, value in FALLBACK.items() if name.endswith("Health")}
        assert len(health) == 14
        assert sorted(health.values()) == list(range(11777, 11791))

    def test_a_status_is_reported_by_name_beside_its_number(self):
        feature = type("F", (), {"Name": "Extrusion1", "Suppressed": False})()
        entry = com.ComBackend._health_entry(feature, 11781)
        assert entry == {"feature": "Extrusion1", "health_status": 11781,
                         "status": "kInErrorHealth", "suppressed": False}

    def test_a_number_the_page_does_not_list_is_not_guessed_at(self):
        feature = type("F", (), {"Name": "Fillet1", "Suppressed": False})()
        assert com.ComBackend._health_entry(feature, 12345)["status"] == "unrecognised"


class TestTheNamesTheDrawingSurfaceAsksFor:
    """The drawing code refers to orientations and styles by their documented
    names and resolves them through `_k`. On a machine whose type library
    cannot be read, a name absent from the table raises -- so every name the
    code can ask for has to be in it."""

    def test_every_view_orientation_and_style_the_backend_names_is_in_the_table(self):
        for name in com.ComBackend._VIEW_ORIENTATIONS.values():
            assert name in FALLBACK, name
        for name in com.ComBackend._VIEW_STYLES.values():
            assert name in FALLBACK, name

    def test_front_is_out_of_sequence_as_the_page_says(self):
        """A table regenerated by hand from a guess at the sequence would put
        Front first. The page says 10764, and so does the library."""
        assert FALLBACK["kFrontViewOrientation"] == 10764
        assert FALLBACK["kBottomViewOrientation"] == 10757
        assert FALLBACK["kLeftViewOrientation"] == 10758

    def test_the_constraint_status_enum_is_complete(self):
        assert FALLBACK["kOverConstrainedConstraintStatus"] == com._OVER_CONSTRAINED == 51715
        assert FALLBACK["kUnknownConstraintStatus"] == 51716


class TestRetrievalFiltersBeforeItRetrieves:
    """The drawing surface used to retrieve every model dimension and then ask
    each *drawing* dimension for its parameter -- a property nothing documents.
    `Sheet.GetRetrievableAnnotations2` hands back the *model's* dimension
    constraints first, and a `DimensionConstraint.Parameter` is documented, so
    the choice is made there. This is the pure half of that."""

    def test_only_asked_for_parameters_are_chosen(self):
        named = [("a", "plate_w"), ("b", "plate_l"), ("c", "hole_d"), ("d", None)]
        chosen = com._annotations_wanted(named, {"plate_w": False, "hole_d": True})
        assert chosen == [("a", "plate_w"), ("c", "hole_d")]

    def test_one_dimension_per_parameter(self):
        """A parameter driving a sketch dimension and a feature dimension would
        otherwise put the same number on the sheet twice."""
        named = [("sketch", "plate_t"), ("feature", "plate_t")]
        assert com._annotations_wanted(named, {"plate_t": False}) == [("sketch", "plate_t")]

    def test_an_annotation_naming_no_parameter_is_never_kept(self):
        """Keeping it would be the "every dimension the model happens to hold"
        the whole route exists to avoid."""
        assert com._annotations_wanted([("x", None)], {"anything": False}) == []

    def test_the_model_side_parameter_is_read_where_it_is_documented(self):
        constraint = type("D", (), {"Parameter": type("P", (), {"Name": "plate_w"})()})()
        assert com._model_parameter_name(constraint) == "plate_w"
        proxy = type("Px", (), {"NativeObject": constraint})()
        assert com._model_parameter_name(proxy) == "plate_w"
        assert com._model_parameter_name(object()) is None

    def test_the_expression_is_read_beside_the_name(self):
        """Measured on 2027.1, 2026-09-08: the names Inventor offered were
        `d0, d1, d4, d5, d6, d7, d8, d9`. A sketch dimension is driven by a
        *model* parameter, and the user parameter a recipe asks for is what
        that model parameter's expression is -- so a match on the name alone
        found nothing on a real part and the whole design read as
        unmeasurable."""
        parameter = type("P", (), {"Name": "d4", "Expression": "plate_w"})()
        constraint = type("D", (), {"Parameter": parameter})()
        assert com._model_parameter(constraint) == ("d4", "plate_w")
        proxy = type("Px", (), {"NativeObject": constraint})()
        assert com._model_parameter(proxy) == ("d4", "plate_w")
        assert com._model_parameter(object()) == (None, None)

    def test_a_parameter_a_dimension_merely_mentions_is_not_stated(self):
        """The distinction the whole match rests on. `plate_w` states 120;
        `plate_w - 2 * edge_margin` states 96, which is neither of the numbers
        the names in it are worth -- and the shipped drawing recipe records
        exactly that about `edge_margin`."""
        wanted = ["plate_w", "edge_margin", "thk"]
        assert com._states_parameter("plate_w", wanted) == "plate_w"
        assert com._states_parameter("plate_w * 1 mm", wanted) == "plate_w"
        assert com._states_parameter("(thk)", wanted) == "thk"
        assert com._states_parameter("plate_w - 2 * edge_margin", wanted) is None
        assert com._states_parameter("2 * plate_w", wanted) is None
        assert com._states_parameter("plate_w + 0", wanted) is None
        assert com._states_parameter("120 mm", wanted) is None
        assert com._states_parameter(None, wanted) is None

    def test_a_model_parameter_is_matched_through_its_expression(self):
        """The name is `d4` and the recipe said `plate_w`, so the name match
        fails and the expression match is what finds it."""
        named = [("a", "d4"), ("b", "d5"), ("c", "d6")]
        expressions = ["plate_w", "plate_w - 2 * edge_margin", "thk"]
        chosen = com._annotations_wanted(
            named, {"plate_w": False, "thk": True}, expressions)
        assert chosen == [("a", "plate_w"), ("c", "thk")]

    def test_a_direct_name_match_still_wins(self):
        """A recipe may name a parameter that drives a dimension itself, and
        the expression route must not have displaced that."""
        named = [("a", "plate_w")]
        assert com._annotations_wanted(named, {"plate_w": False}, [None]) == \
            [("a", "plate_w")]

    def test_one_dimension_per_parameter_through_the_expression_too(self):
        """Two model parameters both being `plate_w` is two dimensions of the
        same number, and a draughtsman writes each one once."""
        named = [("a", "d4"), ("b", "d8")]
        chosen = com._annotations_wanted(named, {"plate_w": False},
                                         ["plate_w", "plate_w"])
        assert chosen == [("a", "plate_w")]

    def test_the_legacy_routes_are_still_there_for_an_older_release(self):
        """2026.1 introduced the pair; the fallback is what a 2025 seat gets."""
        assert com.ComBackend._RETRIEVAL_ROUTES == ("RetrieveDimensions", "AddRetrievedDimensions")


class TestConvexityFromTheBody:
    """`SurfaceBody.ConvexEdges` / `ConcaveEdges` are Inventor's own answer.
    They sit *behind* the measured boundary-loop method, and in front of the
    sampled fallback, which is the order the decision in `DECISIONS.md` gives."""

    @staticmethod
    def edge(key):
        return type("Edge", (), {"TransientKey": key})()

    @staticmethod
    def body(convex, concave):
        def collection(keys):
            edges = [TestConvexityFromTheBody.edge(k) for k in keys]
            return type("Coll", (), {"Count": len(edges),
                                     "Item": staticmethod(lambda i: edges[i - 1])})()
        return type("Body", (), {"ConvexEdges": collection(convex),
                                 "ConcaveEdges": collection(concave)})()

    def test_the_index_is_read_once_per_body_by_transient_key(self):
        index = com._convexity_index([self.body([1, 2], [3]), self.body([7], [])])
        assert index == {"convex": {1, 2, 7}, "concave": {3}}

    def test_an_unreadable_collection_means_no_index_not_an_empty_one(self):
        assert com._convexity_index([object()]) is None

    def test_the_body_answers_where_the_loops_cannot(self):
        """A full circle has no endpoints to orient a loop by -- the
        `flanged_shaft` chamfer that could never ask for ``convex``."""
        index = {"convex": {5}, "concave": {6}}
        assert com._convexity_from_body(self.edge(5), index) == "convex"
        assert com._convexity_from_body(self.edge(6), index) == "concave"

    def test_an_edge_in_neither_or_both_is_unknown(self):
        index = {"convex": {5}, "concave": {5}}
        assert com._convexity_from_body(self.edge(5), index) is None
        assert com._convexity_from_body(self.edge(9), index) is None
        assert com._convexity_from_body(self.edge(9), None) is None

    def test_edge_convexity_reports_the_body_as_its_method(self):
        """An edge with no uses and no faces: the loops cannot look, and the
        old fallback would sample nothing. The body's collections decide."""
        edge = type("Edge", (), {"TransientKey": 5})()
        assert com._edge_convexity(edge, {"convex": {5}, "concave": set()}) == ("convex", "body")

    def test_without_an_index_nothing_changes(self):
        edge = type("Edge", (), {"TransientKey": 5})()
        assert com._edge_convexity(edge) == (None, "sampled")


class TestWorkPlaneKindsAgree:
    """Defect 12: the schema accepts four work-plane kinds, and until 2026-09-08
    two of them built an *offset* plane and reported success. Three places say
    which are buildable and they have to agree.

    Both came off the unbuildable list on 2026-09-09 -- `angle` gained an
    `axis` field and `AddByLinePlaneAndAngle` to call, `tangent` a `face`
    selector and `AddByPlaneAndTangent` -- so the list is empty now and this
    class checks that it stays empty *and* that nothing warns about a kind the
    backend builds."""

    def schema_kinds(self) -> set[str]:
        from inventor_mcp.schema import WorkPlaneOp

        return set(WorkPlaneOp.model_fields["kind"].annotation.__args__)

    def test_the_backend_builds_every_kind_the_schema_accepts(self):
        from inventor_mcp.rehearsal import _KNOWN_BROKEN_FIELDS

        unbuildable = self.schema_kinds() - set(com.ComBackend._WORK_PLANE_KINDS)
        assert unbuildable == set()
        assert ("work_plane", "kind") not in _KNOWN_BROKEN_FIELDS, (
            "nothing about `kind` is broken now, and `kind` has a default -- so "
            "an entry here would warn about every offset plane in every recipe.")

    def _rehearsed(self, plane: dict) -> list[str]:
        from inventor_mcp.builder import rehearse
        from inventor_mcp.schema import PartRecipe

        report = rehearse(PartRecipe.model_validate({
            "name": "P", "units": "mm", "operations": [
                {"op": "sketch", "name": "Base", "plane": "xy", "entities": [
                    {"type": "rectangle", "center": [0, 0], "width": 40, "height": 20}]},
                {"op": "extrude", "sketch": "Base", "distance": 6},
                plane]}))
        return [w["warning"] for w in report["warnings"]]

    def test_no_kind_warns_because_the_backend_builds_all_four(self):
        """A warning about a kind the backend builds is worse than no warning:
        it teaches a caller to avoid the thing that would have worked. `angle`
        and `tangent` were both on the list until 2026-09-09."""
        for plane in (
            {"op": "work_plane", "name": "Tilt", "kind": "angle", "base": "xy",
             "axis": "x", "angle": "30 deg"},
            {"op": "work_plane", "name": "Flat", "kind": "offset", "base": "xy",
             "offset": 5},
        ):
            warnings = self._rehearsed(plane)
            assert [w for w in warnings if "does not work" in w] == [], (plane, warnings)

    def test_each_kind_is_refused_without_the_reference_it_needs(self):
        """There is nothing to default to in either case: a plane turned about
        one of its own directions is a different plane from the same plane
        turned about the other, and a tangent plane is *defined* by the
        cylinder it touches. Defaulting either would be defect 12 again."""
        import pydantic

        from inventor_mcp.schema import WorkPlaneOp

        with pytest.raises(pydantic.ValidationError, match="needs `axis`"):
            WorkPlaneOp(kind="angle", base="xy", angle="30 deg")
        with pytest.raises(pydantic.ValidationError, match="needs `face`"):
            WorkPlaneOp(kind="tangent", base="xy")
        with pytest.raises(pydantic.ValidationError, match="means nothing"):
            WorkPlaneOp(kind="offset", base="xy", axis="x")
        with pytest.raises(pydantic.ValidationError, match="means nothing"):
            WorkPlaneOp(kind="angle", base="xy", axis="x", face={"kind": "face"})

    def test_an_offset_plane_does_not_warn(self):
        from inventor_mcp.builder import rehearse
        from inventor_mcp.schema import PartRecipe

        report = rehearse(PartRecipe.model_validate({
            "name": "P", "units": "mm", "operations": [
                {"op": "sketch", "name": "Base", "plane": "xy", "entities": [
                    {"type": "rectangle", "center": [0, 0], "width": 40, "height": 20}]},
                {"op": "extrude", "sketch": "Base", "distance": 6},
                {"op": "work_plane", "name": "Up", "kind": "offset", "base": "xy",
                 "offset": 10}]}))
        assert [w for w in report["warnings"] if "work_plane" in w["warning"]] == []


class TestThickenFollowsThePublishedCall:
    """`ThickenFeatures.Add(Faces, Distance, ExtentDirection, Operation,
    [AutomaticFaceChain], [CreateVerticalSurfaces], [AutomaticBlending])`, and
    no definition object. The earlier version tried a `CreateThickenDefinition`
    that exists on no release and passed a True into the slot it believed was
    `VerifyResults`, which is `CreateVerticalSurfaces`."""

    def test_no_definition_route_and_no_true_in_an_optional_slot(self):
        """The call is one `_call_named` with the published names in the
        published order. The names are what make the earlier defect
        impossible: `Distance` is a variant and the two enums are integers, so
        a permutation would have built a part rather than raising."""
        import inspect

        source = inspect.getsource(com.ComBackend._add_thicken)
        body = source.split('"""')[-1]
        assert "CreateThickenDefinition" not in body, \
            "the definition route exists on no release"
        names = [line.split('"')[1] for line in body.splitlines()
                 if line.strip().startswith('("')]
        assert names == ["Faces", "Distance", "ExtentDirection", "Operation",
                         "AutomaticFaceChain", "CreateVerticalSurfaces",
                         "AutomaticBlending"]
        assert '("CreateVerticalSurfaces", True)' not in body, \
            "True here adds side faces nothing predicts; it was believed to be VerifyResults"
        assert '("AutomaticFaceChain", False)' in body


class TestThreadFollowsThePublishedCall:
    """`ThreadFeatures.Add(Face, StartEdge, ThreadInfo, ...)`; the
    `CreateThreadDefinition` it used to call exists on no release. Still
    refused by the builder, because the route is unmeasured."""

    def test_the_call_shape_and_the_refusal(self):
        import inspect

        from inventor_mcp.rehearsal import _KNOWN_BROKEN

        source = inspect.getsource(com.ComBackend.thread)
        assert "features.CreateThreadDefinition" not in source
        assert "start_edge" in source and "_thread_info" in source
        assert "thread" in _KNOWN_BROKEN
        assert "CreateStandardThreadInfo" in _KNOWN_BROKEN["thread"]

    def test_the_thread_class_follows_the_table_and_the_side(self):
        """`2B` for an internal inch thread, `6g` for an external metric one --
        the examples on the published page, and case-sensitive as the standards
        write them."""
        assert com._thread_class("ANSI Unified Screw Threads", True) == "2B"
        assert com._thread_class("ANSI Unified Screw Threads", False) == "2A"
        assert com._thread_class("ISO Metric profile", True) == "6H"
        assert com._thread_class("ANSI Metric M Profile", False) == "6g"


class TestMoveFaceFollowsThePublishedDefinition:
    """`MoveFaceDefinition.SetDirectionAndDistanceMoveType` is the published
    setter; the three spellings tried before exist on no release. The type is
    read back, because the page says the definition starts at `kFreeMoveType`."""

    def test_one_setter_and_it_is_the_published_one(self):
        """One name, not a list of candidates. The published page and the live
        `ITypeInfo` read agree on it, which is two sources for a member the
        type library does not publish at all."""
        assert com.ComBackend._MOVE_FACE_SETTER == "SetDirectionAndDistanceMoveType"

    def test_the_move_face_type_enum_is_in_the_table(self):
        assert FALLBACK["kDirectionAndDistanceMoveType"] == 91393
        assert FALLBACK["kPlanarMoveType"] == 91394
        assert FALLBACK["kFreeMoveType"] == 91395

    def test_the_type_is_checked_before_add(self):
        import inspect

        source = inspect.getsource(com.ComBackend.move_face)
        assert "_require_direction_and_distance_type(definition, was)" in source
        assert "was = _move_face_type(definition)" in source, \
            "the type before the setter is what makes the check meaningful"
        assert source.index("_require_direction_and_distance_type") < source.index("features.Add(definition)")

    def test_the_published_argument_order_distance_first_and_flip_as_the_flag(self):
        """`SetDirectionAndDistanceMoveType(Distance, Direction,
        [DirectionReversed])`. The first version of this call had the two the
        other way round, and Distance is a Variant, so a COM object in that slot
        would not have been a type mismatch."""
        import inspect

        assert com.ComBackend._MOVE_FACE_SETTER_ARGUMENTS == (
            "Distance", "Direction", "DirectionReversed")
        source = inspect.getsource(com.ComBackend.move_face)
        assert "(distance, direction, request.flip)" in source, \
            "the values go in in the order the argument names are declared"
        assert "self._MOVE_FACE_SETTER_ARGUMENTS,\n" in source, \
            "named through _call_named, so the order is data rather than a call site"
        assert 'f"-({distance})"' not in source, "flip is the documented flag, not a negated expression"
        assert 'request.direction.kind not in ("work_axis", "edge")' in source


class TestSketchDrivenPatternIsDefinitionBased:
    """`SketchDrivenPatternFeatures.Add(Definition)` per the published page;
    the three-argument `Add` the code used before could never have worked."""

    def test_add_takes_a_definition(self):
        import inspect

        source = inspect.getsource(com.ComBackend.sketch_driven_pattern)
        assert "_sketch_driven_definition(" in source
        assert "features.Add(definition)" in source
        assert "_patterned(features.Add" not in source, \
            "a three-argument Add could never have worked on this release"

        factory = inspect.getsource(com.ComBackend._sketch_driven_definition)
        body = factory.split('"""')[-1]
        names = [line.split('"')[1] for line in body.splitlines()
                 if line.strip().startswith('("')]
        assert names[:3] == ["ParentFeatures", "Sketch", "BasePoint"], names
        assert names[3] == "ReferenceFaces" and '("ReferenceFaces", DEFAULTED)' in body, \
            "nothing in a recipe says reference faces, so Inventor's own default goes in"
        assert "CreateSketchDrivenPatternDefinition" not in body, \
            "measured absent, so it is gone rather than kept as a fallback"
